### ISSUE TITLE
All issue interactions cause NullRef

### ISSUE THREAD

**Issue by talbotmcinnis** [jonas0007/Jira.SDK#28]
I can fetch all project details, but any issue calls cause a NullRef in Newtonsoft.JSON.

Simple Example:
`jiraConn.SearchIssues("project = CM AND fixVersion = 5.2 and issuetype = Release");`

Stacktrace:

```
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Jira.SDK.Domain.IssueSearchResult..ctor(JObject searchResult)
   at Jira.SDK.JiraClient.DeserializeIssues(String json)
   at Jira.SDK.Jira.SearchIssues(String jql)
   at DevWallboard.ViewModels.ReleasesViewModel.<>c__DisplayClass10_0.<GetFromJira>b__1() in 
```

`https://{ourURL}/rest/api/2/search?jql=`

returns lots of stuff.

**Comment by talbotmcinnis** [comment]
This is also in the stack trace and might be relevant:

> {"Value cannot be null.\r\nParameter name: value"}
